services:
  postgres:
    image: postgres:15
    container_name: bookdb
    environment:
      POSTGRES_USER: bookManager
      POSTGRES_PASSWORD: 2025
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bookmanager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookdb
      SPRING_DATASOURCE_USERNAME: bookManager
      SPRING_DATASOURCE_PASSWORD: 2025
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  postgres_data:
